version: '3.1'

services:
  db:
    container_name: currency-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 9999:5432
    networks:
      - backend
  app:
    container_name: currency-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:
    driver: bridge