version: '3.1'

services:
  db:
    container_name: currency-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
  app:
    container_name: currency-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    links:
      - db:db
    depends_on:
      - db